name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          submodules: true
      - uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            apk add cargo gcc linux-headers musl-dev py3-pip python3 python3-dev rust
            ./make.sh
            cp resources/* /home/runner/work/talks/talks/website/
# deploy to github pages
      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: /home/runner/work/talks/talks/website/
          single-commit: true
